# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('exp_date', models.DateTimeField(verbose_name='expiry date')),
                ('job_location', models.CharField(max_length=24)),
                ('job_position', models.CharField(max_length=24)),
                ('job_type', models.CharField(max_length=12)),
                ('job_requirements', models.CharField(max_length=200)),
            ],
        ),
    ]
