# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20160120_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pub_date',
            field=models.DateTimeField(verbose_name='publish date'),
        ),
    ]
