# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20160120_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=32)),
                ('logo', models.URLField(default='None')),
                ('video', models.URLField(default='None')),
                ('website', models.URLField(default='None')),
                ('facebook', models.URLField(default='None')),
                ('twitter', models.URLField(default='None')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobs.Company'),
            preserve_default=False,
        ),
    ]
