# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20160126_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='facebook',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='company',
            name='twitter',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='video',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(),
        ),
    ]
