# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20160126_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='tags',
            field=models.ManyToManyField(blank=True, to='jobs.Tag'),
        ),
    ]
