# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20160202_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='tags',
        ),
        migrations.AddField(
            model_name='company',
            name='slogan',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
