# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20160202_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
    ]
