# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_remove_job_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_location',
        ),
    ]
