# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_remove_job_job_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job_Type',
        ),
        migrations.AddField(
            model_name='job',
            name='job_location',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(default=2, max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='tags',
            field=models.ManyToManyField(blank=True, to='jobs.Tag'),
        ),
    ]
