# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_auto_20160202_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_location',
            field=models.CharField(max_length=24),
        ),
    ]
