# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_auto_20160202_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='initials',
            field=models.CharField(default='CE', max_length=3, unique=True),
            preserve_default=False,
        ),
    ]
