# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_auto_20160208_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(max_length=24),
        ),
    ]
