# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_auto_20160208_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
            ],
        ),
        migrations.RenameModel(
            old_name='Job_Type',
            new_name='Type',
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_type',
            new_name='Type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_requirements',
        ),
    ]
