# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_auto_20160208_2244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointOfInterest',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_location',
        ),
        migrations.AddField(
            model_name='job',
            name='location_name',
            field=models.CharField(default='Costa Rica', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='location_position',
            field=geoposition.fields.GeopositionField(default='Costa Rica', max_length=42),
            preserve_default=False,
        ),
    ]
