# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 19:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0024_auto_20160208_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=5, unique=True, verbose_name='Invitation code')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is code used?')),
                ('is_issued', models.BooleanField(default=False, verbose_name='Has code been issued to someone?')),
                ('used_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Used on')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
