# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_invitationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pub_date',
            field=models.DateTimeField(default=jobs.models.time_now, verbose_name='publish date'),
        ),
    ]
