# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_auto_20160209_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pub_date',
            field=models.DateTimeField(verbose_name='publish date'),
        ),
    ]
