# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 00:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_auto_20160209_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(default=jobs.models.get_token, max_length=60, unique=True, verbose_name='Invitation code'),
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='is_issued',
            field=models.BooleanField(default=False, verbose_name='Issued?'),
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Used?'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='publish date'),
        ),
    ]
