# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 00:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_auto_20160209_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationcode',
            name='issued_date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='Issued on'),
        ),
    ]
