# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_auto_20160209_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='issued_date',
            field=models.DateTimeField(default=jobs.models.time_now, editable=False, verbose_name='Issued on'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pub_date',
            field=models.DateTimeField(default=jobs.models.time_now, editable=False, verbose_name='publish date'),
        ),
    ]
