# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 00:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_auto_20160209_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationcode',
            name='issued_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Used on'),
        ),
    ]
