# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_invitationcode_issued_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='issued_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Used on'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='publish date'),
        ),
    ]
