# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 19:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0034_auto_20160209_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='is_issued',
            field=models.BooleanField(default=True, verbose_name='Issued?'),
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='issued_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Issued on'),
        ),
    ]
