language: python
python:
- '3.4'
- '3.5'
- 3.5-dev
- nightly
install: pip install -r requirements.txt
script: nosetests
deploy:
  provider: heroku
  api_key:
    secure: SZjxVvFY4JwsiH3odIADE2BDmLYfkxAzTYDKMQhP7hGvUQ6zKhnB/JYUiwbyqL2EXgLqL0ZmvsRLyl0azceD7B7BvlqU4w27urivR5IBex41X/nKuwN85o0gTVX5h1YjfnmQ0uXpaeCt5d3ji6GOQ2Vb7zp8PQu3DWn4WOoBeB51ktuO9FjKJMcq8IBOs/kyStzXQOl3w11QfP2MvAMLn33MfkmjX6wQi9sPnFKESVz0j5UeRdsdlFodfbhvE2sv3ySa7YW8p5zeVk+XFCpgomZq4Cx8acG6yaZ14GfRvf3ZM/q3VWvyy981papF14ZKb+GNT6eDRFWraKWXBiSGXPSi+RB/f/VUYEBnjWs3nok5SAFiauiTHA0+kTUt7CO47tULQphCBaMRCFLEjawQa38kiJHDfM4tEdW+Cnf4cW8r1PwhS+haU5VrRJyHWAQ7MrY3P0o38QtnVEPuWTtmEzgu5yDMY9MglGw7J00mqkh8mmPRpGrz/1ZSsM5jKPtE/6TgXffZlmrrjGE6rmDx+ZhTl7mytsPTEdELGua3cfaCqFid39yRHE0VIXfGvpzBCpr9MdQpAlnRnl0JLj5pyZsWkW2mFoJCsd5a1GYtJkhEfFdFaeuJGxjXS1HbZpjF+aFeohsg6IloTlV32M7JmvtkiTOXz02We7Mv9Fp9nI0=
